version: 0.5.1-{build}

branches:
  except:
    - doc

skip_tags: false

platform: x64
configuration: Release

clone_folder: C:\poke-a-mango

install:
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%;C:\Users\appveyor\.cargo\bin
  - bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - bash -lc "pacman --noconfirm -Sy"
  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain"
  -
  - curl -SL https://win.rustup.rs/ -oC:\rustup-init.exe
  - C:\rustup-init.exe -y --default-host="x86_64-pc-windows-gnu"

build: off
build_script:
  - git submodule update --init --recursive
  - cargo build --verbose --release
  - cp target\release\poke-a-mango.exe poke-a-mango-v0.5.1.exe
  - cp target\release\poke-a-mango-tui.exe poke-a-mango-tui-v0.5.1.exe
  - strip --strip-all --remove-section=.comment --remove-section=.note poke-a-mango-v0.5.1.exe
  - strip --strip-all --remove-section=.comment --remove-section=.note poke-a-mango-tui-v0.5.1.exe

test: off
test_script:
  - cargo test --verbose --release

artifacts:
  - path: poke-a-mango-v0.5.1.exe
  - path: poke-a-mango-tui-v0.5.1.exe

deploy:
  provider: GitHub
  artifact: /.*\.exe/
  auth_token:
    secure: JW6d3ZTAKvL6sKdltMr7B232ZiVV2Noc0onZrVKIV7TmmD55LMSa9HTSd0fWcxd+
  on:
    appveyor_repo_tag: true

notifications:
  - provider: Email
    to:
      - nabijaczleweli@gmail.com
    on_build_status_changed: true
