.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "POKE\-A\-MANGO" "1" "January 2017" "poke-a-mango developers" ""
.
.SH "NAME"
\fBpoke\-a\-mango\fR \- What all the kool kidz are playing these days
.
.SH "SYNOPSIS"
\fBpoke\-a\-mango\fR \fIOPTIONS\fR
.
.SH "DESCRIPTION"
Played with your friends or alone, this game provides great entertainment to everyone all over the globe, requiring great eye\-hand coordination and keeping the atmosphere tense\.
.
.P
Exit values and possible errors:
.
.IP "" 4
.
.nf

1 \- Failed to parse a file
2 \- An I/O error occured
3 \- UI failed to cooperate
.
.fi
.
.IP "" 0
.
.SH "OPTIONS"
\-c \-\-config\-dir <\fIconfig_dir\fR>
.
.IP "" 4
.
.nf

Directory with the configuration\.

The configuration directory contains all of poke\-a\-mango\'s data\.

Default: $HOME/\.poke\-a\-mango
.
.fi
.
.IP "" 0
.
.P
\-d \-\-desktop\-size <\fIsize\fR>
.
.IP "" 4
.
.nf

The target desktop\'s resolution\.

By default this is autodetected to match the primary monitor\'s resolution,
but can be overriden to scale the game window better\.

Format: NxM
.
.fi
.
.IP "" 0
.
.SH "EXAMPLES"
\fBpoke\-a\-mango\fR \fB\-d\fR \fI1280x720\fR
.
.IP "" 4
.
.nf

Run the game as on an HD monitor\.
.
.fi
.
.IP "" 0
.
.P
\fBpoke\-a\-mango\fR \fB\-c\fR \fIpkmngo\fR
.
.IP "" 4
.
.nf

Save the game data in "pkmngo" directory instead of the default one\.
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Written by nabijaczleweli <\fInabijaczleweli@gmail\.com\fR> and Andre Bogus <\fIbogusandre@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/nabijaczleweli/poke\-a\-mango/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/nabijaczleweli/poke\-a\-mango\fR>
